# Cambiar a valores comentados para la navegacion sin mapa SLAM.

global_costmap:
  global_frame: robot_odom #map
  robot_base_frame: robot_base_link
  update_frequency: 5.0
  static_map: false #true
  rolling_window: true #false
  resolution: 0.05 

  plugins:

    - name: obstacle_laser_layer
      type: "costmap_2d::VoxelLayer"
    - name: obstacle_camera_layer
      type: "costmap_2d::VoxelLayer"
#    - name: static_map
#      type: "costmap_2d::StaticLayer"
#    - name: inflation_layer
#      type: "costmap_2d::InflationLayer"

#  static_map:
#      static_map: false
 #     map_topic: /rtabmap/grid_map
#      subscribe_to_updates: true
 #     unknown_cost_value: -1
#      trinary_costmap: true
 #     use_maximum: false
#